version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: geo-user
      POSTGRES_PASSWORD: geo-password
      POSTGRES_DB: geo_database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: niawkung@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pg-password
