version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: geo-user
      POSTGRES_PASSWORD: geo-password
      POSTGRES_DB: geo_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: niawkung@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pg-password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/config:/etc/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
